# My first workflow inspired from Noah MLOps

name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependenceies
      run: make install
    - name: Add remote
      env:
        HF: ${{secrets.HF}}
      run: git remote add space https://huggingface.co/spaces/YogyaCh/Trail1
    - name: Push to hub
      env:
        HF: ${{secrets.HF}}
      run: git push --force https://huggingface.co/spaces/YogyaCh/Trail1 main
      
    
    
    
