# My first workflow inspired from Noah MLOps

name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Add remote
      env:
        HF: ${{secrets.HF}}
      run: git remote add space https://YogyaCh:$HF@huggingface.co/spaces/YogyaCh/Trail1
    - name: Push to hub
      env:
        HF: ${{secrets.HF}}
      run: git push --force https://YogyaCh:$HF@huggingface.co/spaces/YogyaCh/Trail1 main
      
    
    
    
