# My first workflow inspired from Noah MLOps

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependenceies
    - run: make install
      
    
    
    
